id: medcom.dk.xdsmetadata
canonical: http://medcomfhir.dk/ig/xdsmetadata
name: Danish profile of the IHE XDS Metadata Standard
title: Danish profile of the IHE XDS Metadata Standard
description: XDS metadata for document sharing in Denmark
status: "draft" # draft | active | retired | unknown
version: "2.0.0-trial-use-1"
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: trial-use # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
publisher:
  name: MedCom
  url: http://www.medcom.dk

menu:
  Home: index.html
  DK XDS Metadata profile:
    DK XDS Metadata profile 1.0.0: XDS_Metadata_for_Document_Sharing_Danish_profile_v.1.0.0.html
    DK XDS Metadata profile 1.0.1: XDS_Metadata_for_Document_Sharing_Danish_profile_v.1.0.1.html
    DK XDS Metadata profile 2.0.0: XDS_Metadata_for_Document_Sharing_Danish_profile_v.2.0.0.html
    DK XDS Metadata profile 2.0.0 CDA example: XDS_Metadata_for_Document_Sharing_Danish_profile_v.2.0.0_cda.html
    DK XDS Metadata profile 2.0.0 FHIR example: XDS_Metadata_for_Document_Sharing_Danish_profile_v.2.0.0_fhir.html
    DK XDS Metadata profile 2.0.0 ebXML example: XDS_Metadata_for_Document_Sharing_Danish_profile_v.2.0.0_ebxml.html
  DK XDS Metadata Terminology: DK-XDS_Metadata-Value_sets.html
  Artifacts: artifacts.html
  More:
    Table of Contents: toc.html
    Roadmap: roadmap.html
    Downloads: downloads.html
    Dependencies: dependencies.html

parameters:
  apply-version: false
  default-version: true
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
  pin-canonicals: pin-multiples
  excludettl: true
  show-inherited-invariants: false
  special-url: [urn:oid:1.2.208.184.100.9, urn:oid:2.16.840.1.113883.6.96, urn:oid:2.16.840.1.113883.6.1, urn:oid:1.2.208.184.100.1, urn:oid:1.2.208.176.2.4, urn:oid:1.2.208.176.2.1, urn:oid:1.2.208.176.7.3.1, urn:oid:1.2.208.184.100.10, urn:oid:1.2.208.176.8.1, urn:oid:2.16.840.1.113883.6.121, urn:oid:2.16.840.1.113883.5.79, urn:oid:1.2.208.184.100.8]
