id: medcom.fhir.dk.xdsmetadata
canonical: http://medcomfhir.dk/ig/xdsmetadata
name: Terminology for XDS Metadata
title: Dk Terminology for XDS Metadata
description: MedCom Terminology for XDS Metadata
status: draft # draft | active | retired | unknown
version: 1.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: release # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: MedCom
  url: http://www.medcom.dk
contact:
  - name: MedCom FHIR Team
    telecom:
      - system: email
        value: fhir@medcom.dk
        use: work

parameters:
  show-inherited-invariants: false
  special-url: [urn:oid:1.2.208.184.100.9, urn:oid:2.16.840.1.113883.6.96, urn:oid:2.16.840.1.113883.6.1, urn:oid:1.2.208.184.100.1, urn:oid:1.2.208.176.2.4, urn:oid:1.2.208.176.2.1, urn:oid:1.2.208.176.7.3.1, urn:oid:1.2.208.184.100.10, urn:oid:1.2.208.176.8.1, urn:oid:2.16.840.1.113883.6.121, urn:oid:2.16.840.1.113883.5.79]

menu:
  Home: index.html
  DK XDS Metadata profile 1.0: XDS_Metadata_for_Document_Sharing_Danish_profile_v.1.0.0.html
  DK XDS Metadata Terminology: DK-IHE_Metadata-Value_sets.html
  Roadmap: roadmap.html
  Artifacts: artifacts.html
  Downloads: downloads.html