ValueSet: MedCom_XDS_TypeCode
Id: MedCom-xds-typecode-VS
Title: "DK XDS TypeCode ValueSet"
Description: "ValueSet containing TypeCode."
* ^version = "1.0.0"
* ^experimental = false
* ^status = #active
* ^date = "2026-01-15"
* $LoincOID#53576-5 // "Personal health monitoring report Document"
* $LoincOID#74468-0 // "Questionnaire Form Definition Document"
* $LoincOID#56446-8 // "Appointment Summary Document"
* $LoincOID#39289-4 // "Follow-up (referred to) provider /specialist, appointment date CPHS"
* $LoincOID#39290-2 // "Follow-up (referred to) program, appointment date CPHS"
* $LoincOID#103140-0 // "Personal health attachment Document"
* $LoincOID#74465-6 // "Questionnaire Response Document"
* $LoincOID#55188-7 // "Patient data Document"
* $LoincOID#11450-4 // "Problem List"
* $LoincOID#81215-6 // "Care plan - recommended C-CDA R2.0 & R2.1 sections"
* $LoincOID#11502-2 // "Laboratory report"
* $LoincOID#57059-8 // "Pregnancy visit summary note Narrative"
* $LoincOID#28615-3 // "Audiology Study"
* $LoincOID#11524-6 // "EKG study"
* $LoincOID#75503-3 // "Patient’s Home Note"
* MedCom_XDS_TypeCode_CS#CMR // "Clinical Mesurement Report"
* MedCom_XDS_TypeCode_CS#PDC // "Stamkort"
* MedCom_XDS_TypeCode_CS#MADC // "MADC"
* MedCom_XDS_TypeCode_CS#PRF // "Pregnancy Referral Form"
* MedCom_XDS_TypeCode_CS#PSCR // "Pregnancy Shared Care Report"
* MedCom_XDS_TypeCode_CS#PMR // "Pregnancy Measurement Report"
* MedCom_XDS_TypeCode_CS#HCOM // "HomeCareObservation message"
